[package]
name = "IsWiped"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows-drives = "0.5.0"
sysinfo = "0.26.8"
itertools = "0.10.5"
gptman = "1.0.0"